---
- hosts: jmeter
  become: yes
  tasks:

    - name: Download Jmeter
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
        dest: /home/ubuntu/
    
    - name: Unarchive Jmeter
      ansible.builtin.shell: tar -xvf ./apache-jmeter-5.6.2.tgz  

    - name: Rename to jmeter
      ansible.builtin.shell: mv ./apache-jmeter-5.6.2 ./jmeter  